using System.Collections.Generic;
using TheFallenWastes_Domain.Entities;
using TheFallenWastes_Domain.Enums;

namespace TheFallenWastes_Domain.UnitFactory
{
    public static class UnitFactory
    {
        public static List<Unit> CreateStarterUnits()
        {
            return new List<Unit>
            {
                // BARRACKS
                new Unit(
                    "Scavenger",
                    "Cheap wasteland survivor. Weak alone, dangerous in numbers.",
                    "Early raid filler",
                    UnitCategory.Infantry,
                    ProductionFacility.Barracks,
                    CombatDamageType.Ballistic,
                    "scavenger",
                    10, 5, 4, 3,
                    14,
                    1,
                    10,
                    1,
                    240,
                    new UnitCost(food: 40, water: 30)
                ),
                new Unit(
                    "Raider",
                    "Fast assault infantry specialized in hit-and-run attacks.",
                    "Fast raid infantry",
                    UnitCategory.Infantry,
                    ProductionFacility.Barracks,
                    CombatDamageType.Ballistic,
                    "raider",
                    16, 6, 4, 3,
                    18,
                    1,
                    14,
                    1,
                    270,
                    new UnitCost(food: 70, water: 50)
                ),
                new Unit(
                    "Outpost Defender",
                    "Core settlement defender trained to hold the line behind walls.",
                    "Defensive core unit",
                    UnitCategory.Infantry,
                    ProductionFacility.Barracks,
                    CombatDamageType.Impact,
                    "outpost-defender",
                    8, 16, 12, 7,
                    10,
                    2,
                    2,
                    2,
                    330,
                    new UnitCost(food: 90, water: 70)
                ),
                new Unit(
                    "Rifleman",
                    "Reliable all-round infantry with stable battlefield performance.",
                    "All-round infantry",
                    UnitCategory.Ranged,
                    ProductionFacility.Barracks,
                    CombatDamageType.Ballistic,
                    "rifleman",
                    18, 9, 7, 5,
                    12,
                    2,
                    6,
                    2,
                    360,
                    new UnitCost(food: 80, water: 70, scrap: 40)
                ),
                new Unit(
                    "Shock Fighter",
                    "Close-range bruiser built to smash through defending lines.",
                    "Assault infantry",
                    UnitCategory.Heavy,
                    ProductionFacility.Barracks,
                    CombatDamageType.Impact,
                    "shock-fighter",
                    22, 8, 10, 5,
                    12,
                    3,
                    4,
                    2,
                    450,
                    new UnitCost(food: 100, water: 80, scrap: 60)
                ),
                new Unit(
                    "Sniper",
                    "Precision marksman focused on high-value enemy targets.",
                    "Ranged specialist",
                    UnitCategory.Ranged,
                    ProductionFacility.Barracks,
                    CombatDamageType.Ballistic,
                    "sniper",
                    28, 5, 4, 5,
                    11,
                    3,
                    4,
                    3,
                    510,
                    new UnitCost(food: 120, water: 90, scrap: 80)
                ),
                new Unit(
                    "Flame Trooper",
                    "Area denial infantry effective against swarms and defenders.",
                    "Anti-swarm infantry",
                    UnitCategory.Heavy,
                    ProductionFacility.Barracks,
                    CombatDamageType.Impact,
                    "flame-trooper",
                    24, 9, 8, 4,
                    10,
                    3,
                    2,
                    3,
                    540,
                    new UnitCost(food: 110, water: 90, fuel: 90)
                ),
                new Unit(
                    "Power Trooper",
                    "Elite power-armored soldier with excellent frontline staying power.",
                    "Heavy elite infantry",
                    UnitCategory.Heavy,
                    ProductionFacility.Barracks,
                    CombatDamageType.Impact,
                    "power-trooper",
                    32, 14, 11, 9,
                    9,
                    4,
                    6,
                    4,
                    660,
                    new UnitCost(food: 130, water: 100, scrap: 120, energy: 80)
                ),

                // GARAGE
                new Unit(
                    "Assault Bike",
                    "Light vehicle for fast military pressure and map control.",
                    "Light vehicle harassment",
                    UnitCategory.Vehicle,
                    ProductionFacility.Garage,
                    CombatDamageType.Ballistic,
                    "assault-bike",
                    20, 8, 5, 4,
                    22,
                    2,
                    12,
                    2,
                    390,
                    new UnitCost(scrap: 100, fuel: 70)
                ),
                new Unit(
                    "Rust Buggy",
                    "Fast wasteland buggy built for plunder and pursuit.",
                    "Fast vehicle raider",
                    UnitCategory.Vehicle,
                    ProductionFacility.Garage,
                    CombatDamageType.Ballistic,
                    "rust-buggy",
                    24, 9, 6, 5,
                    24,
                    3,
                    24,
                    3,
                    480,
                    new UnitCost(scrap: 140, fuel: 90)
                ),
                new Unit(
                    "War Rig",
                    "Heavy assault vehicle used as the backbone of larger attacks.",
                    "Main assault vehicle",
                    UnitCategory.Vehicle,
                    ProductionFacility.Garage,
                    CombatDamageType.Impact,
                    "war-rig",
                    38, 14, 10, 8,
                    13,
                    5,
                    30,
                    5,
                    840,
                    new UnitCost(scrap: 220, fuel: 150, energy: 60)
                ),
                new Unit(
                    "Interceptor",
                    "Mobile hunter specialized in destroying armored targets and support lines.",
                    "Anti-vehicle hunter",
                    UnitCategory.Vehicle,
                    ProductionFacility.Garage,
                    CombatDamageType.Energy,
                    "interceptor",
                    27, 10, 8, 8,
                    17,
                    4,
                    8,
                    4,
                    720,
                    new UnitCost(scrap: 180, fuel: 130, energy: 90)
                ),
                new Unit(
                    "Siege Carrier",
                    "Slow armored platform that supports heavy breach operations.",
                    "Siege backbone",
                    UnitCategory.Transport,
                    ProductionFacility.Garage,
                    CombatDamageType.Impact,
                    "siege-carrier",
                    18, 16, 13, 8,
                    7,
                    6,
                    10,
                    5,
                    960,
                    new UnitCost(scrap: 260, fuel: 180, energy: 80)
                ),

                // WORKSHOP
                new Unit(
                    "Wall Breaker",
                    "Dedicated siege unit designed to tear through perimeter fortifications.",
                    "Anti-structure siege",
                    UnitCategory.Siege,
                    ProductionFacility.Workshop,
                    CombatDamageType.Impact,
                    "wall-breaker",
                    20, 8, 9, 6,
                    7,
                    4,
                    0,
                    4,
                    780,
                    new UnitCost(scrap: 180, fuel: 120, energy: 120)
                ),
                new Unit(
                    "EMP Launcher",
                    "Disruption platform that fries electronics and weakens advanced defenses.",
                    "Disruption support",
                    UnitCategory.Support,
                    ProductionFacility.Workshop,
                    CombatDamageType.Energy,
                    "emp-launcher",
                    19, 7, 6, 10,
                    8,
                    4,
                    0,
                    4,
                    720,
                    new UnitCost(scrap: 140, energy: 110, rareTech: 20)
                ),
                new Unit(
                    "Laser Squad",
                    "Advanced precision team armed with unstable laser weaponry.",
                    "Tech damage dealer",
                    UnitCategory.Ranged,
                    ProductionFacility.Workshop,
                    CombatDamageType.Energy,
                    "laser-squad",
                    31, 8, 6, 11,
                    10,
                    4,
                    4,
                    4,
                    750,
                    new UnitCost(food: 100, water: 80, energy: 120, rareTech: 25)
                ),
                new Unit(
                    "Rad Bomber",
                    "Heavy bombardment unit for breaking dense defensive formations.",
                    "Heavy artillery",
                    UnitCategory.Siege,
                    ProductionFacility.Workshop,
                    CombatDamageType.Energy,
                    "rad-bomber",
                    42, 8, 6, 10,
                    6,
                    5,
                    0,
                    5,
                    1080,
                    new UnitCost(scrap: 160, fuel: 120, energy: 130, rareTech: 35)
                ),
                new Unit(
                    "Drone Swarm",
                    "Autonomous strike drones used for harassment and flanking pressure.",
                    "Mobile tech harassment",
                    UnitCategory.Support,
                    ProductionFacility.Workshop,
                    CombatDamageType.Energy,
                    "drone-swarm",
                    25, 6, 4, 9,
                    19,
                    3,
                    6,
                    3,
                    630,
                    new UnitCost(scrap: 100, energy: 80, rareTech: 20)
                ),

                // COMMAND CENTER
                new Unit(
                    "Scout Drone",
                    "Recon platform used for battlefield awareness and movement intelligence.",
                    "Scouting and intel",
                    UnitCategory.Scout,
                    ProductionFacility.CommandCenter,
                    CombatDamageType.Energy,
                    "scout-drone",
                    2, 2, 1, 3,
                    26,
                    1,
                    0,
                    1,
                    300,
                    new UnitCost(energy: 40, rareTech: 10)
                ),
                new Unit(
                    "Convoy",
                    "Strategic convoy used both to found a new settlement and to claim an enemy settlement after a successful siege.",
                    "Expansion and takeover unit",
                    UnitCategory.Colony,
                    ProductionFacility.CommandCenter,
                    CombatDamageType.None,
                    "convoy",
                    0, 6, 6, 6,
                    5,
                    8,
                    0,
                    6,
                    1800,
                    new UnitCost(food: 300, water: 300, scrap: 240, fuel: 160, energy: 120, rareTech: 50)
                )
            };
        }
    }
}