using System;
using System.Collections.Generic;
using System.Linq;

namespace TheFallenWastes_Domain.Entities
{
    public class SettlementSalvageInventory
    {
        public Guid Id { get; private set; }
        public Guid SettlementId { get; private set; }

        /// <summary>
        /// All salvage item stacks currently stored for this settlement.
        /// </summary>
        public ICollection<SalvageItem> Items { get; private set; }

        /// <summary>
        /// Optional recovered materials generated by salvage processing.
        /// These can later be split into their own entity if needed.
        /// </summary>
        public int StoredRareTech { get; private set; }
        public int StoredResearchData { get; private set; }

        public DateTime UpdatedAtUtc { get; private set; }

        private SettlementSalvageInventory()
        {
            Items = new List<SalvageItem>();
        }

        public SettlementSalvageInventory(Guid settlementId)
        {
            if (settlementId == Guid.Empty)
                throw new ArgumentException("SettlementId cannot be empty.", nameof(settlementId));

            Id = Guid.NewGuid();
            SettlementId = settlementId;
            Items = new List<SalvageItem>();
            StoredRareTech = 0;
            StoredResearchData = 0;
            UpdatedAtUtc = DateTime.UtcNow;
        }

        public IReadOnlyCollection<SalvageItem> GetAllItems()
        {
            return Items
                .OrderBy(i => i.Rarity)
                .ThenBy(i => i.Name)
                .ToList();
        }

        public SalvageItem? GetByKey(string key)
        {
            if (string.IsNullOrWhiteSpace(key))
                return null;

            return Items.FirstOrDefault(i =>
                i.Key.Equals(key.Trim(), StringComparison.OrdinalIgnoreCase));
        }

        public bool HasItem(string key, int quantity = 1)
        {
            if (string.IsNullOrWhiteSpace(key) || quantity <= 0)
                return false;

            var item = GetByKey(key);
            return item != null && item.Quantity >= quantity;
        }

        public void AddItem(SalvageItem item)
        {
            if (item == null)
                throw new ArgumentNullException(nameof(item));

            if (item.SettlementId != SettlementId)
                throw new InvalidOperationException("Salvage item does not belong to this settlement.");

            var existing = GetByKey(item.Key);
            if (existing != null)
            {
                existing.AddQuantity(item.Quantity);
            }
            else
            {
                Items.Add(item);
            }

            UpdatedAtUtc = DateTime.UtcNow;
        }

        public void AddItem(
            string key,
            string name,
            string description,
            string sourceType,
            string rarity,
            int quantity,
            int requiredTechSalvagerLevel,
            int baseSalvageTimeSeconds,
            int rareTechYield,
            int researchDataYield,
            string? specialOutputKey = null)
        {
            var existing = GetByKey(key);
            if (existing != null)
            {
                existing.AddQuantity(quantity);
            }
            else
            {
                Items.Add(new SalvageItem(
                    settlementId: SettlementId,
                    key: key,
                    name: name,
                    description: description,
                    sourceType: sourceType,
                    rarity: rarity,
                    quantity: quantity,
                    requiredTechSalvagerLevel: requiredTechSalvagerLevel,
                    baseSalvageTimeSeconds: baseSalvageTimeSeconds,
                    rareTechYield: rareTechYield,
                    researchDataYield: researchDataYield,
                    specialOutputKey: specialOutputKey
                ));
            }

            UpdatedAtUtc = DateTime.UtcNow;
        }

        public void RemoveItem(string key, int quantity)
        {
            if (string.IsNullOrWhiteSpace(key))
                throw new ArgumentException("Item key cannot be empty.", nameof(key));

            if (quantity <= 0)
                throw new ArgumentException("Quantity must be greater than zero.", nameof(quantity));

            var existing = GetByKey(key);
            if (existing == null)
                throw new InvalidOperationException($"No salvage item found for key '{key}'.");

            existing.RemoveQuantity(quantity);

            if (existing.Quantity <= 0)
            {
                Items.Remove(existing);
            }

            UpdatedAtUtc = DateTime.UtcNow;
        }

        public int GetTotalItemStacks()
        {
            return Items.Count;
        }

        public int GetTotalItemQuantity()
        {
            return Items.Sum(i => i.Quantity);
        }

        public void AddRecoveredOutputs(int rareTech, int researchData)
        {
            if (rareTech < 0)
                throw new ArgumentException("RareTech cannot be negative.", nameof(rareTech));

            if (researchData < 0)
                throw new ArgumentException("ResearchData cannot be negative.", nameof(researchData));

            StoredRareTech += rareTech;
            StoredResearchData += researchData;
            UpdatedAtUtc = DateTime.UtcNow;
        }

        public void ConsumeRecoveredResearchData(int amount)
        {
            if (amount < 0)
                throw new ArgumentException("Amount cannot be negative.", nameof(amount));

            if (amount > StoredResearchData)
                throw new InvalidOperationException("Not enough stored research data.");

            StoredResearchData -= amount;
            UpdatedAtUtc = DateTime.UtcNow;
        }

        public void ConsumeRecoveredRareTech(int amount)
        {
            if (amount < 0)
                throw new ArgumentException("Amount cannot be negative.", nameof(amount));

            if (amount > StoredRareTech)
                throw new InvalidOperationException("Not enough stored RareTech.");

            StoredRareTech -= amount;
            UpdatedAtUtc = DateTime.UtcNow;
        }
    }
}