// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheFallenWastes_Infrastructure;

#nullable disable

namespace TheFallenWastes_Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260317101457_AddPlayerRelations")]
    partial class AddPlayerRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConstructionEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConstructionStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConstructing")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.PlayerRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "TargetPlayerId")
                        .IsUnique();

                    b.ToTable("PlayerRelations");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastResourceTickUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Morale")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<int>("PopulationCapacity")
                        .HasColumnType("int");

                    b.Property<int>("UsedPopulation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Building", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Settlement", null)
                        .WithMany("Buildings")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Settlement", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Player", null)
                        .WithMany("Settlements")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TheFallenWastes_Domain.ValueObjects.ResourceStock", "Resources", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Energy")
                                .HasColumnType("int")
                                .HasColumnName("Energy");

                            b1.Property<int>("Food")
                                .HasColumnType("int")
                                .HasColumnName("Food");

                            b1.Property<int>("Fuel")
                                .HasColumnType("int")
                                .HasColumnName("Fuel");

                            b1.Property<int>("RareTech")
                                .HasColumnType("int")
                                .HasColumnName("RareTech");

                            b1.Property<int>("Scrap")
                                .HasColumnType("int")
                                .HasColumnName("Scrap");

                            b1.Property<int>("Water")
                                .HasColumnType("int")
                                .HasColumnName("Water");

                            b1.HasKey("SettlementId");

                            b1.ToTable("Settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.Navigation("Resources")
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Player", b =>
                {
                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Settlement", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
