// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheFallenWastes_Infrastructure;

#nullable disable

namespace TheFallenWastes_Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260403000001_AddWastelandCoins")]
    partial class AddWastelandCoins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Alliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FoundedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FounderPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("Alliances");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AllianceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInvitation")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.ToTable("AllianceApplications");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceForumPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("AllianceForumPosts");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceForumTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AllianceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.ToTable("AllianceForumTopics");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AllianceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanBroadcast")
                        .HasColumnType("bit");

                    b.Property<bool>("CanInvite")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageRecruitment")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageReservations")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForumModerator")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("AllianceMembers");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConstructionEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConstructionStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConstructing")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.BuildingUpgradeQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CostEnergy")
                        .HasColumnType("int");

                    b.Property<int>("CostFood")
                        .HasColumnType("int");

                    b.Property<int>("CostFuel")
                        .HasColumnType("int");

                    b.Property<int>("CostRareTech")
                        .HasColumnType("int");

                    b.Property<int>("CostScrap")
                        .HasColumnType("int");

                    b.Property<int>("CostWater")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiveBuildingId");

                    b.HasIndex("SettlementId", "IsStarted", "TargetLevel");

                    b.ToTable("BuildingUpgradeQueueItems");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivesAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AttackerSettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LootIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<int>("LootItemsCollected")
                        .HasColumnType("int");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaidMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScoutRareTech")
                        .HasColumnType("int");

                    b.Property<string>("SentUnitsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetPoiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetPoiLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetSettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AllianceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttackScore")
                        .HasColumnType("int");

                    b.Property<int>("AvailableWarPoints")
                        .HasColumnType("int");

                    b.Property<bool>("CommanderActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CommanderExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataVersion")
                        .HasColumnType("int");

                    b.Property<int>("DefenseScore")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("QuartermasterActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("QuartermasterExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<bool>("ScoutMasterActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ScoutMasterExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TechPriestActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TechPriestExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TriumphPoints")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WarlordActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("WarlordExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WastelandCoins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.PlayerRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "TargetPlayerId")
                        .IsUnique();

                    b.ToTable("PlayerRelations");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.PoiState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClearedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenerationSeed")
                        .HasColumnType("int");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInitialized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRelocating")
                        .HasColumnType("bit");

                    b.Property<string>("LootItemsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextRespawnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NpcUnitsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RelocatingAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PoiStates");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Research", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaseDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResearching")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("RareTechCost")
                        .HasColumnType("int");

                    b.Property<int>("RequiredTechLabLevel")
                        .HasColumnType("int");

                    b.Property<int>("ResearchPointCost")
                        .HasColumnType("int");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "Key")
                        .IsUnique();

                    b.ToTable("Researches");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.ResearchQueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("QueueOrder")
                        .HasColumnType("int");

                    b.Property<string>("ResearchKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SettlementResearchStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SettlementResearchStateId", "SlotIndex", "QueueOrder");

                    b.ToTable("ResearchQueueEntries");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.SalvageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("BaseSalvageTimeSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RareTechYield")
                        .HasColumnType("int");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RequiredTechSalvagerLevel")
                        .HasColumnType("int");

                    b.Property<int>("ResearchDataYield")
                        .HasColumnType("int");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SettlementSalvageInventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpecialOutputKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "Key")
                        .IsUnique();

                    b.ToTable("SalvageItems");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastResourceTickUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Morale")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitInventory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UnitInventory");

                    b.Property<int>("VaultRareTech")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.SettlementResearchState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxConcurrentResearches")
                        .HasColumnType("int");

                    b.Property<int>("ResearchPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId")
                        .IsUnique();

                    b.ToTable("SettlementResearchStates");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.SettlementSalvageInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StoredRareTech")
                        .HasColumnType("int");

                    b.Property<int>("StoredResearchData")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId")
                        .IsUnique();

                    b.ToTable("SettlementSalvageInventories");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Siege", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttackerPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConvoyOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefenderPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GarrisonUnitsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AttackerPlayerId");

                    b.HasIndex("DefenderPlayerId");

                    b.HasIndex("SettlementId", "Status");

                    b.ToTable("Sieges");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.UnitTrainingQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveredQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PopulationCostPerUnit")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "IsCompleted", "EndsAtUtc");

                    b.ToTable("UnitTrainingQueueItems");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceApplication", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Alliance", null)
                        .WithMany("Applications")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceForumPost", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.AllianceForumTopic", null)
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceForumTopic", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Alliance", null)
                        .WithMany("ForumTopics")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceMember", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Alliance", null)
                        .WithMany("Members")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Building", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Settlement", null)
                        .WithMany("Buildings")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.BuildingUpgradeQueueItem", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Settlement", "Settlement")
                        .WithMany()
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Research", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.SettlementResearchState", null)
                        .WithMany("Researches")
                        .HasForeignKey("SettlementId")
                        .HasPrincipalKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.ResearchQueueEntry", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.SettlementResearchState", null)
                        .WithMany()
                        .HasForeignKey("SettlementResearchStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.SalvageItem", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.SettlementSalvageInventory", null)
                        .WithMany("Items")
                        .HasForeignKey("SettlementId")
                        .HasPrincipalKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Settlement", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Player", null)
                        .WithMany("Settlements")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TheFallenWastes_Domain.ValueObjects.ResourceStock", "Resources", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Energy")
                                .HasColumnType("int")
                                .HasColumnName("Energy");

                            b1.Property<int>("Food")
                                .HasColumnType("int")
                                .HasColumnName("Food");

                            b1.Property<int>("Fuel")
                                .HasColumnType("int")
                                .HasColumnName("Fuel");

                            b1.Property<int>("RareTech")
                                .HasColumnType("int")
                                .HasColumnName("RareTech");

                            b1.Property<int>("Scrap")
                                .HasColumnType("int")
                                .HasColumnName("Scrap");

                            b1.Property<int>("Water")
                                .HasColumnType("int")
                                .HasColumnName("Water");

                            b1.HasKey("SettlementId");

                            b1.ToTable("Settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.Navigation("Resources")
                        .IsRequired();
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.UnitTrainingQueueItem", b =>
                {
                    b.HasOne("TheFallenWastes_Domain.Entities.Settlement", "Settlement")
                        .WithMany("TrainingQueue")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Alliance", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ForumTopics");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.AllianceForumTopic", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Player", b =>
                {
                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.Settlement", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("TrainingQueue");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.SettlementResearchState", b =>
                {
                    b.Navigation("Researches");
                });

            modelBuilder.Entity("TheFallenWastes_Domain.Entities.SettlementSalvageInventory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
